### ISSUE TITLE
Node periodically stops syncing to latest block

### ISSUE THREAD

**Issue by 8f0d4015198521d2c2b191eabf** [theQRL/qrl-docker#6]
Hi, I'm running a QRL docker node on my linux machine, and I'm noticing that it periodically stops syncing, and I would need to restart the container to trigger it into syncing again. Here're some logs:

```
$ sudo docker exec -it qrl-node qrl --json state
{
  "info": {
    "blockHeight": "1374188",
    "blockLastHash": "fKMPR3lfP9J4cHSuyYgbQh4/eyaVS6s9WZYTVwIAAAA=",
    "networkId": "The sleeper must awaken",
    "numConnections": 24,
    "numKnownPeers": 29,
    "state": "SYNCED",
    "uptime": "225869",
    "version": "2.0.5 python"
  }
}
```
as of the time of writing, based on the block explorer the latest block height is 1374730. And it's been stuck on this height for at least one hour.

**Comment by jplomas** [comment]
My first guesses would be that your base container max size has been reached or the volume on which the container is stored is out of space.  These would be the first things to check.

**Comment by 8f0d4015198521d2c2b191eabf** [comment]
```
sudo docker ps --size
CONTAINER ID   IMAGE                        COMMAND                  CREATED       STATUS      PORTS                                                    NAMES      SIZE
2c0c5dbac4b7   qrledger/qrl-docker:bionic   "/bin/bash -c start_…"   10 days ago   Up 2 days   18090-18091/tcp, 19000/tcp, 19007-19010/tcp, 52134/tcp   qrl-node   6.56GB (virtual 7.37GB)
```
It doesn't seem that the running container's size exceeds docker's 10GB default limit.

I'm running a fresh ubuntu install on a 512Gb SSD, so I doubt it's the size of the volume (unless for some reason docker mounts on a shrunk volume, I'm a docker newbie). And after restarting the node with
```
sudo docker restart 2c0c5dbac4b7
```
the node starts syncing again, now the block height is at 1374771, uptime resets, And the size of the container now says 7.38GB.
```
sudo docker exec -it qrl-node qrl --json state

{
  "info": {
    "blockHeight": "1374774",
    "blockLastHash": "r5cG8GNLpORfdXNyqMopnAwFlI0yMmYeAIpytgEAAAA=",
    "networkId": "The sleeper must awaken",
    "numConnections": 24,
    "numKnownPeers": 29,
    "state": "SYNCED",
    "uptime": "337",
    "version": "2.0.5 python"
  }
}
sudo docker ps --size                         
CONTAINER ID   IMAGE                        COMMAND                  CREATED       STATUS         PORTS                                                    NAMES      SIZE
2c0c5dbac4b7   qrledger/qrl-docker:bionic   "/bin/bash -c start_…"   10 days ago   Up 5 minutes   18090-18091/tcp, 19000/tcp, 19007-19010/tcp, 52134/tcp   qrl-node   6.58GB (virtual 7.38GB)
```

**Comment by 8f0d4015198521d2c2b191eabf** [comment]
Checked it again, and same thing happened, the node stopped syncing (but confirmed that there is internet access). 
```
"info": {
    "blockHeight": "1376745",
    "blockLastHash": "h6RgwTCXRe7FWPoaUrJRvMIDNsz4W2SDh2XPCgEAAAA=",
    "networkId": "The sleeper must awaken",
    "numConnections": 17,
    "numKnownPeers": 29,
    "state": "SYNCED",
    "uptime": "238368",
    "version": "2.0.5 python"
  }
}
```
Latest block at 1378792.

I suspect it's either a networking or a docker issue. Maybe periodically my access to the internet drops, and that causes the node to fall out of sync and stops it from resyncing. I installed `ping` in the docker container, will see if when it's out of sync if there is no internet access.

**Comment by 8f0d4015198521d2c2b191eabf** [comment]
I've updated docker and confirmed that there is network access within the docker image using ping, but the issue persists; it's currently stuck and not updating blocks, at block # 1413097. 

There probably was a point in time where the network dropped. But now that it's back, it should get back to syncing with the network, right?

**Comment by 8f0d4015198521d2c2b191eabf** [comment]
Ok I confirmed that for some reason the internet dropped for more than 20 mins at some point during the night. Weird, I'll look into that. But my question is still, now that it's back, shouldn't it resync with the network automatically?

**Comment by jplomas** [comment]
Closing this stale issue. Feel free to re-open if this has persisted.
